/***  SPEED***/
WITH vars AS (
  SELECT 
    DATEADD(MONTH, -1, DATE_TRUNC('MONTH', CURRENT_DATE())) AS start_date,
    CURRENT_DATE() AS end_date
)

SELECT 
    TO_DATE(HstAKOrder.DATEOFBUSINESS) AS DATEOFBUSINESS, 
    HstAKOrder.FKSTOREID,
    SUBSTR(DIM_STORE.MMX_STORENAME, 1,9) AS MMX_NUMSTORE,
    DIM_PERIODPLANNING.PERIODE_PLANNING,
    DIM_PERIODPLANNING.MOIS,
    DIM_PERIODPLANNING.JOUR,
    DIM_PERIODPLANNING.CATEGORY,
    (CASE 
        WHEN OrderMode.Name LIKE '%B>%' THEN 'Kiosk'
        ELSE 'Drive' 
    END) AS "Canal", 
    (CASE 
        WHEN ((HOUR(HSTAKORDER.TIMESTARTED)*100) + MINUTE(HSTAKORDER.TIMESTARTED)*1) BETWEEN 1200 AND 1400 THEN 'Rush midi'
        ELSE (CASE 
            WHEN ((HOUR(HSTAKORDER.TIMESTARTED)*100) + MINUTE(HSTAKORDER.TIMESTARTED)*1) BETWEEN 1900 AND 2100 THEN 'Rush soir'
            ELSE 'Hors Rush'                
        END)
    END) AS DAYPART,
    AVG(LASTTIMEBUMPED) / 86400 AS "Temps Total vd"
FROM 
    KFC_FRANCE_DL_DEV.NCR.HSTAKORDER  
    INNER JOIN KFC_FRANCE_DL_DEV.NCR.OrderMode ON OrderMode.OrderModeId = HstAKOrder.FKOrderModeID
    INNER JOIN KFC_FRANCE_DW_DEV.DWH.DIM_STORE ON DIM_STORE.ID_STORE = HstAKOrder.FKSTOREID
    LEFT JOIN  KFC_FRANCE_DW_DEV.DWH.DIM_PERIODPLANNING ON DIM_PERIODPLANNING.BUSINESSDATE = HstAKOrder.Dateofbusiness
    CROSS JOIN vars 
WHERE 
    HstAKOrder.DATEOFBUSINESS BETWEEN vars.start_date AND vars.end_date
    AND (OrderMode.Name LIKE 'B>%' OR OrderMode.Name LIKE '%Drive%')
    AND DIM_STORE.MMX_STORENAME NOT LIKE '%CLOSED%' 
    AND DIM_STORE.MMX_STORENAME <> ''
    AND lasttimebumped < 3000 AND lasttimebumped > 15
GROUP BY 
    HstAKOrder.DATEOFBUSINESS, 
    HstAKOrder.FKSTOREID,
    DIM_STORE.MMX_STORENAME,
    SUBSTR(DIM_STORE.MMX_STORENAME, 1,9),
    DIM_PERIODPLANNING.PERIODE_PLANNING,
    DIM_PERIODPLANNING.MOIS, 
    DIM_PERIODPLANNING.CATEGORY,
    DIM_PERIODPLANNING.JOUR,
    (CASE 
        WHEN OrderMode.Name LIKE '%B>%' THEN 'Kiosk'
        ELSE 'Drive' 
    END), 
    (CASE 
        WHEN ((HOUR(HSTAKORDER.TIMESTARTED)*100) + MINUTE(HSTAKORDER.TIMESTARTED)*1) BETWEEN 1200 AND 1400 THEN 'Rush midi'
        ELSE (CASE 
            WHEN ((HOUR(HSTAKORDER.TIMESTARTED)*100) + MINUTE(HSTAKORDER.TIMESTARTED)*1) BETWEEN 1900 AND 2100 THEN 'Rush soir'
            ELSE 'Hors Rush'                
        END)
    END)
HAVING 
    HstAKOrder.DATEOFBUSINESS >= '2024-01-01'
     AND HstAKOrder.DATEOFBUSINESS <  DATEADD(DAY, -MOD(DAYOFWEEK(CURRENT_DATE()) + 4, 7), CURRENT_DATE()) 
     AND DAYPART <> 'Hors Rush'

UNION

SELECT 
    TO_DATE(HstAKOrder.DATEOFBUSINESS) AS DATEOFBUSINESS, 
    HstAKOrder.FKSTOREID,
    
    SUBSTR(DIM_STORE.MMX_STORENAME, 1,9) AS MMX_NUMSTORE,
    DIM_PERIODPLANNING.PERIODE_PLANNING,
    DIM_PERIODPLANNING.MOIS,
    DIM_PERIODPLANNING.JOUR,
    DIM_PERIODPLANNING.CATEGORY,
    (CASE 
        WHEN OrderMode.Name LIKE '%B>%' THEN 'Kiosk'
        ELSE 'Drive' 
    END) AS "Canal", 
    'Moyenne Journee' AS "DAYPART",
    AVG(LASTTIMEBUMPED) / 86400 AS "Temps Total vd"
FROM 
    KFC_FRANCE_DL_DEV.NCR.HSTAKORDER  
    INNER JOIN KFC_FRANCE_DL_DEV.NCR.OrderMode ON OrderMode.OrderModeId = HstAKOrder.FKOrderModeID
    INNER JOIN KFC_FRANCE_DW_DEV.DWH.DIM_STORE ON DIM_STORE.ID_STORE = HstAKOrder.FKSTOREID
    LEFT JOIN  KFC_FRANCE_DW_DEV.DWH.DIM_PERIODPLANNING ON DIM_PERIODPLANNING.BUSINESSDATE = HstAKOrder.Dateofbusiness
    CROSS JOIN vars 
WHERE 
    HstAKOrder.DATEOFBUSINESS BETWEEN vars.start_date AND vars.end_date 
    AND (OrderMode.Name LIKE 'B>%' OR OrderMode.Name LIKE '%Drive%')
    AND DIM_STORE.MMX_STORENAME NOT LIKE '%CLOSED%' 
    AND DIM_STORE.MMX_STORENAME <> ''
    AND lasttimebumped < 3000 AND lasttimebumped > 15
GROUP BY 
    (CASE 
        WHEN OrderMode.Name LIKE '%B>%' THEN 'Kiosk'
        ELSE 'Drive' 
    END),
    HstAKOrder.DATEOFBUSINESS, 
    HstAKOrder.FKSTOREID,
    SUBSTR(DIM_STORE.MMX_STORENAME, 1,9),
    DIM_PERIODPLANNING.PERIODE_PLANNING,
    DIM_PERIODPLANNING.MOIS, 
    DIM_PERIODPLANNING.CATEGORY,
    DIM_PERIODPLANNING.JOUR
HAVING 
     HstAKOrder.DATEOFBUSINESS >= '2024-01-01'
     AND HstAKOrder.DATEOFBUSINESS <  DATEADD(DAY, -MOD(DAYOFWEEK(CURRENT_DATE()) + 4, 7), CURRENT_DATE()) ;
